-- GifEmotes_CustomRegistry.lua
-- Auto-generated by GifEmotes Studio

GifEmotes = GifEmotes or {}
GifEmotes.Registry = GifEmotes.Registry or {}

GifEmotes.Registry["awful_umamusume"] = {
    id = "awful_umamusume",
    name = "Awful Umamusume",
    basePath = "media/textures/gifs/awful_umamusume/",
    frameCount = 14,
    fps = 30,
    durationSec = 0.47,
    preview = "media/textures/gifs/awful_umamusume/0.png"
}

GifEmotes.Registry["cafe_manhattan_cafe_uma_umamusume_fish"] = {
    id = "cafe_manhattan_cafe_uma_umamusume_fish",
    name = "Cafe Manhattan Cafe Uma Umamusume Fish",
    basePath = "media/textures/gifs/cafe_manhattan_cafe_uma_umamusume_fish/",
    frameCount = 135,
    fps = 30,
    durationSec = 4.5,
    preview = "media/textures/gifs/cafe_manhattan_cafe_uma_umamusume_fish/0.png"
}

GifEmotes.Registry["fan_blowing_wind_wind_hot_summer"] = {
    id = "fan_blowing_wind_wind_hot_summer",
    name = "Fan Blowing Wind Wind Hot Summer",
    basePath = "media/textures/gifs/fan_blowing_wind_wind_hot_summer/",
    frameCount = 9,
    fps = 30,
    durationSec = 0.3,
    preview = "media/textures/gifs/fan_blowing_wind_wind_hot_summer/0.png"
}

GifEmotes.Registry["meisho_doto_meisho"] = {
    id = "meisho_doto_meisho",
    name = "Meisho Doto Meisho",
    basePath = "media/textures/gifs/meisho_doto_meisho/",
    frameCount = 142,
    fps = 30,
    durationSec = 4.73,
    preview = "media/textures/gifs/meisho_doto_meisho/0.png"
}

GifEmotes.Registry["meisho_doto_tm_opera_o"] = {
    id = "meisho_doto_tm_opera_o",
    name = "Meisho Doto Tm Opera O",
    basePath = "media/textures/gifs/meisho_doto_tm_opera_o/",
    frameCount = 63,
    fps = 30,
    durationSec = 2.1,
    preview = "media/textures/gifs/meisho_doto_tm_opera_o/0.png"
}

GifEmotes.Registry["miyabi_reaction"] = {
    id = "miyabi_reaction",
    name = "Miyabi Reaction",
    basePath = "media/textures/gifs/miyabi_reaction/",
    frameCount = 37,
    fps = 30,
    durationSec = 1.23,
    preview = "media/textures/gifs/miyabi_reaction/0.png"
}

GifEmotes.Registry["ramielle_ramielle_zzz"] = {
    id = "ramielle_ramielle_zzz",
    name = "Ramielle Ramielle Zzz",
    basePath = "media/textures/gifs/ramielle_ramielle_zzz/",
    frameCount = 54,
    fps = 30,
    durationSec = 1.8,
    preview = "media/textures/gifs/ramielle_ramielle_zzz/0.png"
}

GifEmotes.Registry["remielle_dance"] = {
    id = "remielle_dance",
    name = "Remielle Dance",
    basePath = "media/textures/gifs/remielle_dance/",
    frameCount = 102,
    fps = 30,
    durationSec = 3.4,
    preview = "media/textures/gifs/remielle_dance/0.png"
}

GifEmotes.Registry["stay_gold_stay"] = {
    id = "stay_gold_stay",
    name = "Stay Gold Stay",
    basePath = "media/textures/gifs/stay_gold_stay/",
    frameCount = 30,
    fps = 30,
    durationSec = 1.0,
    preview = "media/textures/gifs/stay_gold_stay/0.png"
}

GifEmotes.Registry["stay_gold_stay_gold_running"] = {
    id = "stay_gold_stay_gold_running",
    name = "Stay Gold Stay Gold Running",
    basePath = "media/textures/gifs/stay_gold_stay_gold_running/",
    frameCount = 9,
    fps = 30,
    durationSec = 0.3,
    preview = "media/textures/gifs/stay_gold_stay_gold_running/0.png"
}

GifEmotes.Registry["stay_gold_uma_musume_sad"] = {
    id = "stay_gold_uma_musume_sad",
    name = "Stay Gold Uma Musume Sad",
    basePath = "media/textures/gifs/stay_gold_uma_musume_sad/",
    frameCount = 92,
    fps = 30,
    durationSec = 3.07,
    preview = "media/textures/gifs/stay_gold_uma_musume_sad/0.png"
}

GifEmotes.Registry["umamusume_agnes_tachyon_yes_nod_uma_musume"] = {
    id = "umamusume_agnes_tachyon_yes_nod_uma_musume",
    name = "Umamusume Agnes Tachyon Yes Nod Uma Musume",
    basePath = "media/textures/gifs/umamusume_agnes_tachyon_yes_nod_uma_musume/",
    frameCount = 9,
    fps = 30,
    durationSec = 0.3,
    preview = "media/textures/gifs/umamusume_agnes_tachyon_yes_nod_uma_musume/0.png"
}

GifEmotes.Registry["umamusume_satono_diamond_lick_funny"] = {
    id = "umamusume_satono_diamond_lick_funny",
    name = "Umamusume Satono Diamond Lick Funny",
    basePath = "media/textures/gifs/umamusume_satono_diamond_lick_funny/",
    frameCount = 57,
    fps = 30,
    durationSec = 1.9,
    preview = "media/textures/gifs/umamusume_satono_diamond_lick_funny/0.png"
}

GifEmotes.Registry["uma_musume_oguri_cap"] = {
    id = "uma_musume_oguri_cap",
    name = "Uma Musume Oguri Cap",
    basePath = "media/textures/gifs/uma_musume_oguri_cap/",
    frameCount = 169,
    fps = 30,
    durationSec = 5.63,
    preview = "media/textures/gifs/uma_musume_oguri_cap/0.png"
}

GifEmotes.Registry["uma_musume_symboli_rudolf"] = {
    id = "uma_musume_symboli_rudolf",
    name = "Uma Musume Symboli Rudolf",
    basePath = "media/textures/gifs/uma_musume_symboli_rudolf/",
    frameCount = 180,
    fps = 30,
    durationSec = 6.0,
    preview = "media/textures/gifs/uma_musume_symboli_rudolf/0.png"
}

-- Dynamically register texture frames in ZomboidFileSystem (Client-only)
local function registerCustomTextures()
    if isServer and isServer() then return end
    local fs = getZomboidFileSystem and getZomboidFileSystem()
    if not (fs and fs.activeFileMap) then return end

    local docFolder = (getMyDocumentFolder and getMyDocumentFolder()) or (fs.getCacheDir and fs:getCacheDir()) or "Zomboid"
    docFolder = docFolder:gsub("\\", "/")

    local modDir = nil
    if fs.getModDir then
        local ok, val = pcall(function() return fs:getModDir("GifEmotes") end)
        if ok and val then modDir = val end
    end
    if not modDir and getModDirectory then
        local ok, val = pcall(function() return getModDirectory("GifEmotes") end)
        if ok and val then modDir = val end
    end
    if modDir then
        modDir = modDir:gsub("\\", "/")
    end

    if not GifEmotes or not GifEmotes.Registry then return end
    for _, g in pairs(GifEmotes.Registry) do
        if g.basePath and g.frameCount then
            for i = 0, (g.frameCount - 1) do
                local rel = g.basePath .. tostring(i) .. ".png"
                local key = rel:lower():gsub("\\", "/")
                if fs.relativeMap then
                    fs.relativeMap:put(key, key)
                end
                if modDir then
                    fs.activeFileMap:put(key, modDir .. "/" .. rel)
                    fs.activeFileMap:put(rel, modDir .. "/" .. rel)
                    fs.activeFileMap:put(key, modDir .. "/42/" .. rel)
                    fs.activeFileMap:put(rel, modDir .. "/42/" .. rel)
                end
                fs.activeFileMap:put(key, docFolder .. "/mods/GifEmotes/" .. rel)
                fs.activeFileMap:put(rel, docFolder .. "/mods/GifEmotes/" .. rel)
                fs.activeFileMap:put(key, docFolder .. "/mods/GifEmotes/42/" .. rel)
                fs.activeFileMap:put(rel, docFolder .. "/mods/GifEmotes/42/" .. rel)
            end
        end
    end
end
pcall(registerCustomTextures)
